info <- structure(list(water = structure(list(oceans = c("ne_110m_ocean.zip",
"ne_50m_ocean.zip", "ne_10m_ocean.zip", "ne_10m_ocean_scale_rank.zip"
), lakes = c("ne_50m_lakes.zip", "ne_50m_lakes_historic.zip",
"ne_110m_rivers_lake_centerlines.zip", "ne_50m_rivers_lake_centerlines.zip",
"ne_50m_rivers_lake_centerlines_scale_rank.zip", "ne_110m_lakes.zip",
"ne_10m_lakes.zip", "ne_10m_rivers_lake_centerlines.zip",
"ne_10m_rivers_lake_centerlines_scale_rank.zip", "ne_10m_lakes_historic.zip",
"ne_10m_lakes_north_america.zip", "ne_10m_lakes_pluvial.zip",
"ne_10m_lakes_europe.zip"), other = c("ne_10m_reefs.zip",
"ne_10m_geography_marine_polys.zip", "ne_10m_rivers_europe.zip",
"ne_10m_rivers_north_america.zip", "ne_50m_playas.zip",
"ne_50m_coastline.zip", "ne_110m_coastline.zip"), bathymetry = c("ne_10m_bathymetry_A_10000.zip",
"ne_10m_bathymetry_B_9000.zip", "ne_10m_bathymetry_C_8000.zip",
"ne_10m_bathymetry_D_7000.zip", "ne_10m_bathymetry_E_6000.zip",
"ne_10m_bathymetry_F_5000.zip", "ne_10m_bathymetry_G_4000.zip",
"ne_10m_bathymetry_H_3000.zip", "ne_10m_bathymetry_I_2000.zip",
"ne_10m_bathymetry_J_1000.zip", "ne_10m_bathymetry_K_200.zip",
"ne_10m_bathymetry_L_0.zip"), ice = c("ne_10m_glaciated_areas.zip",
"ne_50m_glaciated_areas.zip", "ne_110m_glaciated_areas.zip",
"ne_50m_antarctic_ice_shelves_lines.zip", "ne_50m_antarctic_ice_shelves_polys.zip",
"ne_10m_antarctic_ice_shelves_lines.zip", "ne_10m_antarctic_ice_shelves_polys.zip"
)), .Names = c("oceans", "lakes", "other", "bathymetry", "ice"
)), political = structure(list(countries = c("ne_50m_admin_0_tiny_countries.zip",
"ne_50m_admin_0_tiny_countries_scale_rank.zip", "ne_110m_admin_0_countries.zip",
"ne_10m_admin_0_countries.zip", "ne_10m_admin_0_countries_lakes.zip",
"ne_110m_admin_0_countries_lakes.zip", "ne_50m_admin_0_countries.zip",
"ne_110m_admin_0_tiny_countries.zip", "ne_50m_admin_0_countries_lakes.zip"
), states = c("ne_50m_admin_1_states_provinces.zip", "ne_50m_admin_1_states_provinces_lakes.zip",
"ne_50m_admin_1_states_provinces_lakes_shp.zip", "ne_50m_admin_1_states_provinces_lines.zip",
"ne_50m_admin_1_states_provinces_scale_rank.zip", "ne_50m_admin_1_states_provinces_shp.zip",
"ne_50m_admin_1_states_provinces_shp_scale_rank.zip", "ne_10m_admin_1_states_provinces.zip",
"ne_10m_admin_1_states_provinces_lakes.zip", "ne_10m_admin_1_states_provinces_lakes_shp.zip",
"ne_10m_admin_1_states_provinces_lines.zip", "ne_10m_admin_1_states_provinces_scale_rank.zip",
"ne_10m_admin_1_states_provinces_shp.zip", "ne_110m_admin_1_states_provinces_shp_scale_rank.zip",
"ne_110m_admin_1_states_provinces.zip", "ne_110m_admin_1_states_provinces_lakes.zip",
"ne_110m_admin_1_states_provinces_lakes_shp.zip", "ne_110m_admin_1_states_provinces_lines.zip",
"ne_110m_admin_1_states_provinces_scale_rank.zip", "ne_110m_admin_1_states_provinces_shp.zip"
), boundaries = c("ne_10m_admin_0_boundary_lines_disputed_areas.zip",
"ne_10m_admin_0_boundary_lines_land.zip", "ne_10m_admin_0_boundary_lines_map_units.zip",
"ne_10m_admin_0_boundary_lines_maritime_indicator.zip", "ne_110m_admin_0_boundary_lines_land.zip",
"ne_50m_admin_0_boundary_lines_disputed_areas.zip", "ne_50m_admin_0_boundary_lines_land.zip",
"ne_50m_admin_0_boundary_lines_maritime_indicator.zip", "ne_50m_admin_0_boundary_map_units.zip"
), other = c("ne_110m_admin_0_map_units.zip", "ne_110m_admin_0_pacific_groupings.zip",
"ne_110m_admin_0_scale_rank.zip", "ne_110m_admin_0_sovereignty.zip",
"ne_50m_admin_0_breakaway_disputed_areas.zip", "ne_50m_admin_0_map_subunits.zip",
"ne_50m_admin_0_map_units.zip", "ne_50m_admin_0_pacific_groupings.zip",
"ne_50m_admin_0_scale_rank.zip", "ne_50m_admin_0_sovereignty.zip",
"ne_10m_admin_0_antarctic_claim_limit_lines.zip", "ne_10m_admin_0_antarctic_claims.zip",
"ne_10m_admin_0_disputed_areas.zip", "ne_10m_admin_0_disputed_areas_scale_rank_minor_islands.zip",
"ne_10m_admin_0_label_points.zip", "ne_10m_admin_0_map_subunits.zip",
"ne_10m_admin_0_map_units.zip", "ne_10m_admin_0_pacific_groupings.zip",
"ne_10m_admin_0_scale_rank.zip", "ne_10m_admin_0_scale_rank_minor_islands.zip",
"ne_10m_admin_0_seams.zip", "ne_10m_admin_0_sovereignty.zip",
"ne_10m_admin_1_label_points.zip", "ne_10m_admin_1_seams.zip"
)), .Names = c("countries", "states", "boundaries", "other")),
    people = structure(list(areas = c("ne_50m_urban_areas.zip",
    "ne_10m_populated_places.zip", "ne_10m_populated_places_simple.zip",
    "ne_50m_populated_places.zip", "ne_50m_populated_places_simple.zip",
    "ne_110m_populated_places.zip", "ne_110m_populated_places_simple.zip",
    "ne_10m_urban_areas.zip"), transport = c("ne_10m_airports.zip",
    "ne_10m_ports.zip", "ne_10m_railroads.zip", "ne_10m_roads.zip",
    "ne_10m_railroads_north_america.zip")), .Names = c("areas",
    "transport")), land = structure(list(`all land` = c("ne_10m_land.zip",
    "ne_50m_land.zip", "ne_110m_land.zip"), islands = c("ne_10m_minor_islands.zip",
    "ne_10m_minor_islands_coastline.zip", "ne_10m_minor_islands_label_points.zip"
    ), parks = c("ne_10m_parks_and_protected_lands_area.zip",
    "ne_10m_parks_and_protected_lands_line.zip", "ne_10m_parks_and_protected_lands_point.zip",
    "ne_10m_parks_and_protected_lands_scale_rank.zip"), coasts = c("ne_10m_playas.zip",
    "ne_10m_coastline.zip", "ne_10m_land_ocean_label_points.zip",
    "ne_10m_land_ocean_seams.zip", "ne_10m_land_scale_rank.zip",
    "ne_110m_geography_marine_polys.zip", "ne_50m_geography_marine_polys.zip"
    ), regions = c("ne_50m_geography_regions_elevation_points.zip",
    "ne_50m_geographic_lines.zip", "ne_50m_geography_regions_points.zip",
    "ne_50m_geography_regions_polys.zip", "ne_10m_geography_regions_elevation_points.zip",
    "ne_10m_geography_regions_points.zip", "ne_10m_geography_regions_polys.zip",
    "ne_110m_geography_regions_elevation_points.zip", "ne_10m_geographic_lines.zip",
    "ne_110m_geography_regions_points.zip", "ne_110m_geography_regions_polys.zip"
    )), .Names = c("all land", "islands", "parks", "coasts",
    "regions")), utilities = structure(list(graticules = c("ne_50m_graticules_1.zip",
    "ne_50m_graticules_10.zip", "ne_50m_graticules_15.zip",
    "ne_50m_graticules_20.zip", "ne_10m_graticules_1.zip",
    "ne_10m_graticules_10.zip", "ne_10m_graticules_15.zip",
    "ne_10m_graticules_20.zip", "ne_10m_graticules_30.zip",
    "ne_10m_graticules_5.zip", "ne_50m_graticules_30.zip",
    "ne_50m_graticules_5.zip", "ne_110m_graticules_1.zip",
    "ne_110m_graticules_10.zip", "ne_110m_graticules_15.zip",
    "ne_110m_graticules_20.zip", "ne_110m_graticules_30.zip",
    "ne_110m_graticules_5.zip"), misc = c("ne_10m_time_zones.zip",
    "ne_10m_wgs84_bounding_box.zip", "ne_50m_wgs84_bounding_box.zip",
    "ne_110m_wgs84_bounding_box.zip", "ne_110m_geographic_lines.zip"
    )), .Names = c("graticules", "misc"))), .Names = c("water",
"political", "people", "land", "utilities"))
